version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ez_metric_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ez_metric
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
